Modificando todos los README y solucionando los errores con las variables de los roles

diff --git a/roles/mariadb/templates/mariadb_rotate.j2 b/roles/mariadb/templates/mariadb_rotate.j2
--- a/roles/mariadb/templates/mariadb_rotate.j2
+++ b/roles/mariadb/templates/mariadb_rotate.j2
@@ -1,43 +1,55 @@
 /var/log/mysql/error.log
 {
-	weekly
-	rotate 12
-	missingok
-    notifempty
+  weekly
+  rotate {{ logs_rotation_weekly }}
+  maxsize {{ logs_max_size }}
+  nomissingok
+  notifempty
+  olddir {{ logs_rotated_dir }}/mariadb/
+  createolddir 0640 root root
+
+  compress
+  delaycompress
+  dateext
+  dateyesterday
+
 	create 640 mysql adm
-	compress
-    dateext
-    dateyesterday
 
 	sharedscripts
 	postrotate
-          test -x /usr/bin/mysqladmin || exit 0
-          if [ -f `my_print_defaults --mysqld | grep -m 1 -oP "pid-file=\K.+$"` ]; then
-            # If this fails, check debian.conf!
-            mysqladmin --defaults-file=/etc/mysql/debian.cnf --local flush-error-log \
-              flush-engine-log flush-general-log flush-slow-log
-          fi
+    test -x /usr/bin/mysqladmin || exit 0
+    if [ -f `my_print_defaults --mysqld | grep -m 1 -oP "pid-file=\K.+$"` ]; then
+      # If this fails, check debian.conf!
+      mysqladmin --defaults-file=/etc/mysql/debian.cnf --local flush-error-log \
+        flush-engine-log flush-general-log flush-slow-log
+    fi
 	endscript
 }
 
 /var/log/mysql/mariadb_general.log /var/log/mysql/mariadb_slow.log
 {
-	daily
-	rotate 30
-	missingok
-    notifempty
+  daily
+  rotate {{ logs_rotation_daily }}
+  maxsize {{ logs_max_size }}
+  nomissingok
+  notifempty
+  olddir {{ logs_rotated_dir }}/mariadb/
+  createolddir 0640 root root
+
+  compress
+  delaycompress
+  dateext
+  dateyesterday
+
 	create 640 mysql adm
-	compress
-    dateext
-    dateyesterday
 
 	sharedscripts
 	postrotate
-          test -x /usr/bin/mysqladmin || exit 0
-          if [ -f `my_print_defaults --mysqld | grep -m 1 -oP "pid-file=\K.+$"` ]; then
-            # If this fails, check debian.conf!
-            mysqladmin --defaults-file=/etc/mysql/debian.cnf --local flush-error-log \
-              flush-engine-log flush-general-log flush-slow-log
-          fi
+    test -x /usr/bin/mysqladmin || exit 0
+    if [ -f `my_print_defaults --mysqld | grep -m 1 -oP "pid-file=\K.+$"` ]; then
+      # If this fails, check debian.conf!
+      mysqladmin --defaults-file=/etc/mysql/debian.cnf --local flush-error-log \
+        flush-engine-log flush-general-log flush-slow-log
+    fi
 	endscript
 }
